build_name: extra_changes
strategy_type: Source
architecture: amd64
contextDir: ''
isRos: True
rosDistro: kinetic
SimulationOption: ''
dockerFilePath: ''
secret:
dockerPullSecret:
dockerPushSecret:
dockerPushRepository:
